apiVersion: v1
kind: ServiceAccount
metadata:
  name: wordpress
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: wordpress
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wordpress
  namespace: default
subjects:
- kind: ServiceAccount
  name: wordpress
  apiGroup: ""
roleRef:
  kind: Role
  name: wordpress
  apiGroup: rbac.authorization.k8s.io