apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: winterfell
  region: us-east-2
  version: "1.18"

vpc:
  nat:
    gateway: HighlyAvailable

iam: 
  withOIDC: true

nodeGroups:
  - name: managed-ng-1
    minSize: 1
    maxSize: 3
    desiredCapacity: 1
    privateNetworking: true